# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master", "development" ]
  release:
    branches: [ "master", "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set Up Java
        uses: actions/setup-java@v1
        with:
          java-version: 17
          cache: maven

      # Use cache to speed up build
      - name: Cache Maven Repo
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      # If the cache was not present, run BuildTools to install the relevant versions to Maven.
      # This will take approximately forever.
      - name: Install Spigot Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir ~/buildtools
          cd ~/buildtools
          wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          java -jar BuildTools.jar --rev 1.20.4
      - name: Build With Maven
        run: |
          mvn -e clean package -am -P all
          mkdir staging
          cp target/*.jar staging
      - name: "Upload IG"    
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging

      # Upload artifacts
      - name: Upload Distributable Jar
        id: upload-final
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: target/Punishmental.jar
  release:
    name: Create Github Release
    needs: [ build ]
    if: github.event_name == 'create' && github.event.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./Punishmental.jar
          asset_name: Punishmental.jar
          asset_content_type: application/java-archive
